### ISSUE TITLE
캠페인 기능

### ISSUE THREAD

**Issue by jee14** [Review-Cock/review-cock#2]
## Description
캠페인 내용을 보고, 신청하는 기능을 만든다.

## Todo
- [x] 캠페인 엔티티 모델링 하기
- [x] 캠페인 등록, 조회 기능 구현하기
- [x] 테스트 코드 작성하기
