### ISSUE TITLE
코드 리팩토링

### ISSUE THREAD

**Issue by jee14** [Review-Cock/review-cock#47]
## Description
persistence layer의 memory leak 등의 문제점들을 개선한다.

## Todo
- [ ] 캠페인 조회 시 n+1 문제 개선
- [ ] 캠페인 조회 시 memory leak 문제 개선
- [ ] 더 효율적인 쿼리 고민
