### ISSUE TITLE
캠페인 등록페이지 리팩토링

### ISSUE THREAD

**Issue by dohun2** [Review-Cock/review-cock#55]
## Description
캠페인 등록페이지 리팩토링

## Todo
- [ ] 중복된 코드 제거
- [ ] 상수 분리
- [ ] 총 모집인원 placeholder 보이게 수정
- [ ] 카테고리 기본 값 추가

## ETC
기타사항
